import type { Meta, StoryObj } from "@storybook/react";
import { Icon } from "@/components/Icon/Icon";

const meta = {
  title: "Components/Icon",
  component: Icon,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    type: {
      control: "select",
      options: [
        "XSquare",
        "X",
        "ZoomIn",
        "ZoomOut",
        "Filter",
        "Up",
        "UpLeft",
        "Upload",
        "UpRight",
        "XCircle",
        "ShoppingBag",
        "Star",
        "Tool",
        "Trash2",
        "Save",
        "Search",
        "Share",
        "Plus",
        "Right",
        "MoreVertical",
        "Paperclip",
        "PlusCircle",
        "PlusSquare",
        "MinusCircle",
        "MinusSquare",
        "Minus",
        "MoreHorizontal",
        "MicOff",
        "Mic",
        "List",
        "Loader",
        "Mail",
        "Italic",
        "Left",
        "Link2",
        "Link",
        "Heart",
        "Home",
        "Inbox",
        "Down",
        "DownLeft",
        "Download",
        "DownRight",
        "CheckSquare",
        "Check",
        "Delete",
        "CameraOff",
        "Camera",
        "CheckCircle",
        "Box",
        "Calendar",
        "Bell",
        "BookOpen",
        "Bookmark",
        "BarChart2",
        "BarChart",
        "BellOff",
        "AlignRight",
        "Archive",
        "Arrow",
        "AlignJustify",
        "AlignLeft",
        "AlignCenter",
        "ChevronDown",
      ],
    },
    size: {
      control: { type: "number", min: 16, max: 128, step: 8 },
    },
    className: {
      control: "text",
    },
  },
} satisfies Meta<typeof Icon>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    type: "Search",
    size: 64,
    className: "bg-gray-900",
  },
};
